name: BUILD

on:
  push:
    branches:
      - dev_xiaok
      - master
  pull_request:
    branches:
      - dev_xiaok
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps
        run: npm install

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Prepare Deploy
        if: github.ref == 'refs/heads/dev_xiaok'
        run: |
          cp ./server/config.json ./dist/config.json

      - name: Deploy to Host
        if: github.ref == 'refs/heads/dev_xiaok'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npm run deploy:host:dev
